baseurl = "http://dangdangdotcom.github.io/sharding-jdbc/"
languageCode = "en-us"
title = "Sharding-JDBC"

[params]
    description = "A JDBC driver for shard databases and tables"
    author_url = "https://github.com/dangdangdotcom"
    project_url = "https://github.com/dangdangdotcom/sharding-jdbc"
    project_documentation = "http://dangdangdotcom.github.io/sharding-jdbc"
    github_project_name = "Sharding-JDBC"
    github_user_name = "dangdangdotcom"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"
